# Generated by Django 3.2.22 on 2024-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('sub_img', models.ImageField(blank=True, upload_to='images')),
                ('sub_bg', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
