# Generated by Django 3.2.22 on 2024-05-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sub_bg',
        ),
    ]
