# Generated by Django 3.2.22 on 2024-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0004_alter_subject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
