# Generated by Django 3.2.22 on 2024-05-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0005_subject_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy_list', models.CharField(max_length=300)),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.subject')),
            ],
        ),
    ]
