# Generated by Django 3.2.22 on 2024-05-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0009_alter_syllabus_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qa_app.subject'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='sy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qa_app.syllabus'),
        ),
    ]
