# Generated by Django 3.2.22 on 2024-05-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0010_auto_20240507_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.subject'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='sy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.syllabus'),
        ),
    ]
