# Generated by Django 3.2.22 on 2024-05-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0011_auto_20240507_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sy_list', to='qa_app.subject'),
        ),
    ]
