# Generated by Django 3.2.22 on 2024-05-11 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0012_alter_syllabus_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='sub_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_app.subject'),
        ),
    ]
