# Generated by Django 3.2.22 on 2024-05-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0014_auto_20240513_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='sy_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_set', to='qa_app.syllabus'),
        ),
    ]
