# Generated by Django 3.2.22 on 2024-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0015_alter_qa_sy_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='indo',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
